---
base:
  build: .
  privileged: true
  working_dir: /app/
  volumes:
    - ".:/app"

config:
  extends:
    service: base
  command: lb config

build:
  extends:
    service: base
  command: lb build --quiet

clean:
  extends:
    service: base
  command: lb clean
