---
defaults: &defaults
  build: .
  privileged: true
  working_dir: /app/
  volumes:
    - ".:/app"

config:
  <<: *defaults
  command: lb config

build:
  <<: *defaults
  command: lb build --quiet

clean:
  <<: *defaults
  command: lb clean
